version: '3.7'
services:
  vrgs_nginx:
    build: ./docker/nginx
    container_name: vrgs_nginx
    ports:
      - "100:80"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - .:/var/www/html
      - ./docker/nginx/log/:/var/log/nginx
      - /tmp:/tmp
    depends_on:
      - vrgs_php
    networks:
      - vrgs-net

  vrgs_php:
    build: ./docker/php
    container_name: vrgs_php
    ports:
    - "80:80"
    volumes:
      - .:/var/www/html
      - /tmp:/tmp
      - ~/.composer:/var/www/.composer
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=vrgs_mysql"
    depends_on:
      - vrgs_mysql
    networks:
      - vrgs-net

  vrgs_mysql:
    image: mysql:5.7
    container_name: vrgs_mysql
    ports:
      - "33100:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vrgs
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - vrgs_mysql_data:/var/lib/mysql
    networks:
      - vrgs-net

  vrgs_pma:
    image: phpmyadmin/phpmyadmin
    container_name: vrgs_pma
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - "8100:80"
    volumes:
      - /sessions
    networks:
      - vrgs-net

networks:
  vrgs-net:
volumes:
  vrgs_mysql_data:
